### ISSUE TITLE
space-before-blocks should be an error

### ISSUE THREAD

**Issue by ndhoule** [segmentio/eslint-config#14]
Warning in the short term to prevent builds from breaking, but eventually should be enabled.

Taken from https://github.com/segmentio/eslint-config/issues/7

**Comment by ndhoule** [comment]
Note to self: Enabling this will cause analytics.js-\* repos to fail CI

**Comment by stephenmathieson** [comment]
meh https://github.com/segmentio/eslint-config/issues/16#issuecomment-189019705

**Comment by dominicbarnes** [comment]
auto-fixing is available here, so there's no reason to leave it as a warning

**Comment by ndhoule** [comment]
Resolved in #46
