### ISSUE TITLE
yoda should be an error

### ISSUE THREAD

**Issue by ndhoule** [segmentio/eslint-config#16]
Warning in the short term to prevent builds from breaking, but eventually should be enabled.

Taken from https://github.com/segmentio/eslint-config/issues/7

**Comment by stephenmathieson** [comment]
meh.. i think things that cause errors should be errors.  stylistic things should be warnings.

**Comment by stephenmathieson** [comment]
@ndhoule since we've already 3.0.0'ed, should we remove the 2.0.0 milestone :p

/trolling

**Comment by dominicbarnes** [comment]
I'm ok with stylistic things being errors, because consistency is pretty important imo. I would stick to a warning if we're still migrating a lot of code, or if auto-fixing isn't available.

**Comment by ndhoule** [comment]
Warnings don't make you fix anything. The longer a warning exists the less value the concept of "warning" as a whole has. Warnings are cool to help you gradually converge on a consistent style, but the body of things that are true warnings should be as small as possible.

Not to mention stylistic consistency is pretty valuable.

**Comment by ndhoule** [comment]
Resolved in #46
