### ISSUE TITLE
disallow exclusive mocha tests

### ISSUE THREAD

**Issue by dominicbarnes** [segmentio/eslint-config#33]
To prevent us from accidentally leaving a `describe.only()` behind in our unit tests, I'd like to consider adding a [new plugin](https://github.com/lo1tuma/eslint-plugin-mocha), specifically using this [rule](https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/no-exclusive-tests.md).

**Comment by ndhoule** [comment]
Big +1

**Comment by ndhoule** [comment]
This will be covered in https://github.com/segmentio/eslint-config/pull/39.
