### ISSUE TITLE
version 3 makes everything explode

### ISSUE THREAD

**Issue by stephenmathieson** [segmentio/eslint-config#44]
since b7af1ff48cce4151347c4d69f10d86fe998d035b, all of our `.eslintrc` files are broken

why did we change the name in package.json?

/cc @ndhoule @dominicbarnes

**Comment by stephenmathieson** [comment]
also, having to `npm prune` all the time is getting annoying

**Comment by ndhoule** [comment]
Yes, upgrading to 3.x requires that you update your `.eslintrc` files. You can keep using the 2.x line without issue if you don't want to do that work yet.

> why did we change the name in package.json?

To close https://github.com/segmentio/eslint-config/issues/1 and to make sure that opting into the updated config did not happen automatically even if you were using `*` in your `package.json`.

> also, having to `npm prune` all the time is getting annoying

I'm not sure what to do about that. That's a reality of projects where dependencies change.

**Comment by stephenmathieson** [comment]
ah, didnt realize #1 was a thing

closing since this was a premeditated decision

**Comment by ndhoule** [comment]
Yeah, we just haven't touched the eslint config much in a while; I was reorganizing all of the configs to take advantage of newer/cleaner eslint features and it was going to break eslint `extends` paths anyway, so figured now was time to tear off the band-aid.

**Comment by ndhoule** [comment]
This made me realize that the upgrade process could be a lot clearer—I'm gonna add a `HISTORY.md` with upgrade instructions.

**Comment by stephenmathieson** [comment]
:+1: for a changelog

**Comment by ndhoule** [comment]
Added in b67f37a700b9d1c3ce3591ea1e134100379ae30a
