### ISSUE TITLE
prefer-const

### ISSUE THREAD

**Issue by stephenmathieson** [segmentio/eslint-config#45]
we should stop declaring constants with `let`. there's no reason for it and it causes bugs/headaches

related: https://github.com/segmentio/app/pull/939

**Comment by ndhoule** [comment]
Big +1 from me, I've been doing this everywhere and it's definitely better than `var` or even `let` in most cases.

@dominicbarnes had feelings on `const` vs `let` last we chatted, not sure if those have changed

**Comment by stephenmathieson** [comment]
> dominicbarnes had feelings on const vs let last we chatted, not sure if those have changed

i'll happy argue about the ecmascript spec here if you object @dominicbarnes :p

**Comment by dominicbarnes** [comment]
Haha, I just felt like `const` looks weird, it's totally a subjective/silly thing. I'm not opposed to using it here as long as ESLint will help me keep them consistent.
