### ISSUE TITLE
Warnings that should eventually become errors

### ISSUE THREAD

**Issue by dominicbarnes** [segmentio/eslint-config#7]
To keep from breaking builds in the short-term, we've got some rules we've made into warnings. The end-goal is to only have errors though, so we'll track the warnings that we need to convert here:
- [ ] max-depth
- [ ] max-len
- [ ] max-nested-callbacks
- [ ] max-params
- [ ] object-curly-spacing
- [ ] space-before-blocks
- [ ] valid-jsdoc
- [ ] yoda

**Comment by ndhoule** [comment]
Note to self: `object-curly-braces` and `space-before-blocks` aren't yet merged because it would cause `analytics.js-*` repos to start failing CI

**Comment by ndhoule** [comment]
@dominicbarnes moved all these out into their own issues. Thanks for compiling this list :)
