### ISSUE TITLE
Enable cyclomatic complexity rule

### ISSUE THREAD

**Issue by ndhoule** [segmentio/eslint-config#8]
Singling out a.js-integrations as an example, a lot of our functions do way too much. We should enable `complexity` to prevent this from happening.

http://eslint.org/docs/rules/complexity

Should be a warning at first, and an error down the line. Thinking the setting should be high and we can gradually decrease it.

**Comment by stephenmathieson** [comment]
+1

**Comment by dominicbarnes** [comment]
+1 for a warning

**Comment by ndhoule** [comment]
sweet, let's try it out!
